name:                MCISP2K
version:             0.1.0.0
# github:              "gabriel-siqueira/MCISP2K"
license:             BSD3
author:              "Gabriel Siqueira"
maintainer:          "gabriel.gabrielhs@gmail.com"
copyright:           "2021 Gabriel Siqueira"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:         Please see the README on GitHub at <https://github.com/gabriel-siqueira/MCISP2K#readme>

dependencies:
- base
- MonadRandom
- bytestring
- containers
- deepseq
- hashable
- hedgehog
- lifted-async
- optparse-applicative
- parallel-io
- process
- random
- random-shuffle
- text
- time
- transformers
- unordered-containers
- vector

library:
  source-dirs: src

executables:
  MCISP2K:
    main:                MCISP2K.hs
    source-dirs:         app
    other-modules: []
    ghc-options:
    - -main-is MCISP2K
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - MCISP2K

  DB:
    main:                DB.hs
    source-dirs:         app
    other-modules: []
    ghc-options:
    - -main-is DB
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - MCISP2K

tests:
  MCISP2K-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MCISP2K
